# Generated by Django 3.2.8 on 2021-10-18 21:39

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0002_auto_20211018_1424'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('Account', django.db.models.manager.Manager()),
            ],
        ),
    ]
